### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by Nerevar123** [reaviz/reakeys#11]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
With the new installation of Reaflow I got an infinite loop: 

![image](https://user-images.githubusercontent.com/65253367/140655724-d2e7a285-0055-4c7b-bb0e-2675ec709e09.png)

which happens if using useUndo or useSelection (maybe more)
After a few hours of searching, I found that the problem is with this package. 
The last working version is 1.2.2

## Minimal reproduction of the problem with instructions

Install reaflow - call useSelection like this - 

> function onDataChange(): any {}
> 	
>   const { selections } = useSelection({
>     nodes: [],
>     edges: [],
>     onDataChange,
>   });

**Comment by amcdnl** [comment]
I believe this got introduced recently in some fixes. I have reverted them for now and re-published. Please give that a shot
