### ISSUE TITLE
navigator variable access not protected (undefined during SSR)

### ISSUE THREAD

**Issue by gggard** [reaviz/reakeys#25]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Currently in utils.ts the navigator variable access is not protected against being undefined (for example during SSR with Gatsby)

## Expected behavior
If navigator variable does not exist, just return isMac = false

## What is the motivation / use case for changing the behavior?

Support SSR rendering

## Environment

<pre><code>
Libs:
- react version: 17.x.x
- reakeys version: 1.2.9

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ X ] SSR
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by johnmathews** [comment]
I've encountered this warning also. I assume its not a problem, it doesn't seem to be. 

It would be good to have less verbose console output. The below is repeated many times when i build the site:

```
ReferenceError: navigator is not defined
    at file:///Users/john/Projects/blog/node_modules/reakeys/dist/index.js:95:3
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async DefaultModuleLoader.import (node:internal/modules/esm/loader:228:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:428:15)
```

**Comment by amcdnl** [comment]
This is caused by mousetrap. We are going to move off of it since its not updated recently.
