### ISSUE TITLE
Supporting + character

### ISSUE THREAD

**Issue by SharonGrossman** [reaviz/reakeys#28]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
The requirement I am facing is a hotkey that's triggered by a combination of SHIFT + +
```
useHotkeys([{name: 'hotkey', keys: ['shift++']);
```
This above doesn't work and it seems to be a problem in most hotkey libraries, and the way it's solved is with specifying different combination key for use cases like this.

## Expected behavior
Being able to use shift and + to trigger a callback

## Minimal reproduction of the problem with instructions

```
useHotkeys([{name: 'hotkey', keys: ['shift++']);
```

## What is the motivation / use case for changing the behavior?
This'll allow more combinations and be able to use these characters (-, +) in combinations

Thanks for elegant library, really wanna  use it, and I could help with this issue if it is feasible.

**Comment by amcdnl** [comment]
@SharonGrossman - If you do `shift+plus` does it work? Under the hood this uses mousetrap so you can look at docs for that.

**Comment by SharonGrossman** [comment]
> @SharonGrossman - If you do `shift+plus` does it work? Under the hood this uses mousetrap so you can look at docs for that.

Thanks! works like a charm :)
