### ISSUE TITLE
Migrate off Mousetrap

### ISSUE THREAD

**Issue by amcdnl** [reaviz/reakeys#29]
Mousetrap is old and not maintained anymore. We should move off of it for NextJS support. Some alternatives:

- https://github.com/webNeat/ctrl-keys
- https://github.com/RobertWHurst/Keystrokes
- https://github.com/jamiebuilds/tinykeys
- https://github.com/jaywcjlove/hotkeys-js

Key features we are using in mousetrap ( beyond simple binding ):

- Meta/CMD/CTRL shortcuts
- Focus based shortcuts on elements
- Inputs don't trigger hotkeys

**Comment by evgenoid** [comment]
@amcdnl seems no one library do not support binding hotkey to the specific element

**Comment by C-Higgins** [comment]
Ctrl-keys depends on https://github.com/webNeat/just-types/blob/main/package.json (made by the same guy) which does not properly scope its dev dependencies. This is causing reakeys to pull Typescript into the bundle. Consider just vendoring that dependency to fix it, since it appears dead.

**Comment by C-Higgins** [comment]
Mantine has a functioning implementation that may be copied https://github.com/mantinedev/mantine/blob/master/packages/@mantine/hooks/src/use-hotkeys/use-hotkeys.ts

https://github.com/mantinedev/mantine/blob/master/packages/@mantine/hooks/src/use-hotkeys/use-hotkeys.ts
