### ISSUE TITLE
Feature request - Unregister shortcut

### ISSUE THREAD

**Issue by Vadorequest** [reaviz/reakeys#3]
At this time, it is possible to register new shortcuts using `useHotkeys`, but it doesn't see possible to unregister shortcuts.

Maybe it's possible but not documented? (is that what the `name` property is for?)

**Comment by LoganDark** [comment]
As useHotkeys is declarative, to "unregister a shortcut" you simply stop providing its object in the array.

**Comment by Vadorequest** [comment]
It's been a while, but I think my need was to disable a shortcut that's built-in, hence I couldn't do it this way.

**Comment by LoganDark** [comment]
In your callback, you receive an ExtendedKeyboardEvent which you can call preventDefault on, AFAIK.

**Comment by amcdnl** [comment]
Ironically I implemented this without even realizing to update this comment. Checkout the new readme and you can see how to do it now.
